import { Metadata } from "next";
import React from "react";
import Navbar from "../../components/navbar";
import Footer from "../../components/footer";
import QuotesPage from "../app/quotes/page";
import "./../app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    url: "https://nextjs.org",
    title: "Create Next App",
    description: "Generated by create next app",
  },
  twitter: {
    card: "summary_large_image",
    site: "@vercel",
    creator: "@vercel",
  },
};

export default function Home() {
  return (
    <div className="flex flex-col  min-h-screen p-4 bg-[#f4f1eb]">
      <Navbar />
      <QuotesPage />
      <Footer />
    </div>
  );
}
